# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin.json
name: PatchTheBucket
version: ${version}
main: net.colourlabs.patchthebucket.PatchTheBucket
load: STARTUP
loadbefore: [TestPlugin]
api-version: 1.12