# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin.json
name: PatchTheBucketDemo
version: ${version}
main: net.colourlabs.patchthebucket.demo.DemoPlugin
depend: [PatchTheBucket]
api-version: 1.12
