# yaml-language-server: $schema=https://json.schemastore.org/bukkit-plugin.json
name: TestPlugin
version: ${version}
main: net.colourlabs.testplugin.DummyPlugin
api-version: 1.12

commands:
  test:
    description: Test command that demonstrates various bugs
    usage: /test <add|divide|greet|count>
